
package com.storepoints.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-07-04T12:47:50.022-07:00
 * Generated source version: 2.6.0
 * 
 */
public final class StorePointsService_StorePointsServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.storepoints.com/", "StorePointsService");

    private StorePointsService_StorePointsServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = StorePointsService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        StorePointsService_Service ss = new StorePointsService_Service(wsdlURL, SERVICE_NAME);
        StorePointsService port = ss.getStorePointsServiceImplPort();  
        
        {
        System.out.println("Invoking getUserList...");
        java.lang.String _getUserList_arg0 = "";
        java.lang.String _getUserList_arg1 = "";
        java.util.List<com.storepoints.service.User> _getUserList__return = port.getUserList(_getUserList_arg0, _getUserList_arg1);
        System.out.println("getUserList.result=" + _getUserList__return);


        }
        {
        System.out.println("Invoking getAccounts...");
        java.lang.String _getAccounts_arg0 = "";
        java.lang.String _getAccounts_arg1 = "";
        java.util.List<com.storepoints.service.AccountData> _getAccounts__return = port.getAccounts(_getAccounts_arg0, _getAccounts_arg1);
        System.out.println("getAccounts.result=" + _getAccounts__return);


        }
        {
        System.out.println("Invoking addStore...");
        com.storepoints.service.Store _addStore_arg0 = null;
        com.storepoints.service.Status _addStore__return = port.addStore(_addStore_arg0);
        System.out.println("addStore.result=" + _addStore__return);


        }
        {
        System.out.println("Invoking getStores...");
        java.util.List<com.storepoints.service.Store> _getStores__return = port.getStores();
        System.out.println("getStores.result=" + _getStores__return);


        }

        System.exit(0);
    }

}
