package com.storepoints.service;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-16T05:53:36.467-07:00
 * Generated source version: 2.6.0
 * 
 */
@WebService(targetNamespace = "http://service.storepoints.com/", name = "StorePointsService")
@XmlSeeAlso({ObjectFactory.class})
public interface StorePointsService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getAccounts", targetNamespace = "http://service.storepoints.com/", className = "com.storepoints.service.GetAccounts")
    @WebMethod
    @ResponseWrapper(localName = "getAccountsResponse", targetNamespace = "http://service.storepoints.com/", className = "com.storepoints.service.GetAccountsResponse")
    public java.util.List<com.storepoints.service.Account> getAccounts(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );
}
