
package com.storepoints.service;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-06-16T05:53:36.420-07:00
 * Generated source version: 2.6.0
 * 
 */
public final class StorePointsService_StorePointsServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://service.storepoints.com/", "StorePointsService");

    private StorePointsService_StorePointsServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = StorePointsService_Service.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        StorePointsService_Service ss = new StorePointsService_Service(wsdlURL, SERVICE_NAME);
        StorePointsService port = ss.getStorePointsServiceImplPort();  
        
        {
        System.out.println("Invoking getAccounts...");
        java.lang.String _getAccounts_arg0 = "";
        java.util.List<com.storepoints.service.Account> _getAccounts__return = port.getAccounts(_getAccounts_arg0);
        System.out.println("getAccounts.result=" + _getAccounts__return);


        }

        System.exit(0);
    }

}
