package com.storepoints.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.6.0
 * 2012-07-04T12:47:50.108-07:00
 * Generated source version: 2.6.0
 * 
 */
@WebServiceClient(name = "StorePointsService", 
                  wsdlLocation = "schema/StorePointsService.wsdl",
                  targetNamespace = "http://service.storepoints.com/") 
public class StorePointsService_Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://service.storepoints.com/", "StorePointsService");
    public final static QName StorePointsServiceImplPort = new QName("http://service.storepoints.com/", "StorePointsServiceImplPort");
    static {
        URL url = StorePointsService_Service.class.getResource("schema/StorePointsService.wsdl");
        if (url == null) {
            java.util.logging.Logger.getLogger(StorePointsService_Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "schema/StorePointsService.wsdl");
        }       
        WSDL_LOCATION = url;
    }

    public StorePointsService_Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public StorePointsService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public StorePointsService_Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns StorePointsService
     */
    @WebEndpoint(name = "StorePointsServiceImplPort")
    public StorePointsService getStorePointsServiceImplPort() {
        return super.getPort(StorePointsServiceImplPort, StorePointsService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns StorePointsService
     */
    @WebEndpoint(name = "StorePointsServiceImplPort")
    public StorePointsService getStorePointsServiceImplPort(WebServiceFeature... features) {
        return super.getPort(StorePointsServiceImplPort, StorePointsService.class, features);
    }

}
